Q1

In [50]:
#1
import numpy as np
A = np.array([ [12, 5, 8, 20], [ 7, 15, 3, 11], [25, 9, 18, 6], [10, 14, 2, 16] ])  
print(np.mean(A,axis=1))

[11.25  9.   14.5  10.5 ]

In [51]:
#2,3,4
A=np.where(A>np.mean(A,axis=1),1,0)
print(A)

[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]

#5
every row contains equal no. of elements above the average

Q2

In [52]:
#1
X = np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15, 115, 9] ]) 
print(np.mean(X,axis=0))
print(np.std(X,axis=0))

[ 12.5        173.           6.83333333]
[  1.70782513 146.31017281   1.34370962]

In [53]:
#2
condition=np.abs(X-np.mean(X,axis=0))>2*np.std(X,axis=0)
print(X[condition])

[500]

In [54]:
#3,4
np.where(condition,np.median(X,axis=0),X)

array([[ 10., 100.,   5.],
       [ 12., 110.,   6.],
       [ 11., 105.,   7.],
       [ 13., 109.,   6.],
       [ 14., 108.,   8.],
       [ 15., 115.,   9.]])

Q3

In [55]:
#1
import pandas as pd  
df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],  'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],  'Gender': ['F','M','F','M','M','F','F','M'],  'Marks': [85,72,91,65,78,88,95,70], 'Attendance': [92,81,96,72,85,90,98,75] }) 
print(df.groupby("Department")["Marks"].mean())

Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64

In [56]:
#2
print(df.groupby(["Department","Gender"])["Marks"].mean())

Department  Gender
CSE         F         90.0
            M         75.0
ECE         F         89.5
            M         67.5
Name: Marks, dtype: float64

In [57]:
#3
h=df.groupby("Department")["Marks"].idxmax()
print(df.loc[h,"Student"])

6    G
2    C
Name: Student, dtype: str

In [58]:
#4
g=df.groupby("Department")["Marks"].mean()
df["avg"]=df["Department"].map(g)
print(df[df["Marks"]>df["avg"]])

  Student Department Gender  Marks  Attendance   avg
0       A        CSE      F     85          92  82.5
2       C        ECE      F     91          96  78.5
5       F        ECE      F     88          90  78.5
6       G        CSE      F     95          98  82.5

In [59]:
#5
print(df.groupby("Department")["Attendance"].mean().idxmax())

CSE

Q4

In [60]:
#1
df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],  'Name': ['A','B','C','A','D','B','E'], 'Age': [20,21,22,20,23,21,24],  'Score': [80,75,90,85,88,75,92] }) 
print(df["ID"],df["ID"].duplicated())

0    101
1    102
2    103
3    101
4    104
5    102
6    105
Name: ID, dtype: int64 0    False
1    False
2    False
3     True
4    False
5     True
6    False
Name: ID, dtype: bool

In [61]:
#3
df.groupby("ID")[["Name","Age","Score"]].nunique()

     Name  Age  Score
ID
101     1    1      2
102     1    1      1
103     1    1      1
104     1    1      1
105     1    1      1

In [62]:
#4
new_df=df.loc[df.groupby("ID")["Score"].idxmax()]
new_df

    ID Name  Age  Score
3  101    A   20     85
1  102    B   21     75
2  103    C   22     90
4  104    D   23     88
6  105    E   24     92

In [63]:
#5
print(df.shape[0]-new_df.shape[0])

2

Q5

In [64]:
#1
df = pd.DataFrame({ 'Date': [ '2026-01-01', '2026-01-02', '2026-01-04', '2026-01-05', '2026-01-08', '2026-01-09' ],  'Sales': [100,120,150,130,180,200] })  
df['Date']=pd.to_datetime(df["Date"])
df

        Date  Sales
0 2026-01-01    100
1 2026-01-02    120
2 2026-01-04    150
3 2026-01-05    130
4 2026-01-08    180
5 2026-01-09    200

In [65]:
#2
print([date for date in pd.date_range(df["Date"].min(),df["Date"].max()) if date not in df["Date"].values])

[Timestamp('2026-01-03 00:00:00'), Timestamp('2026-01-06 00:00:00'), Timestamp('2026-01-07 00:00:00')]

In [ ]:
#4
df=df.set_index("Date")
df=df.reindex(pd.date_range(df.index.min(),df.index.max()))

In [68]:
#3
df

            Sales
2026-01-01  100.0
2026-01-02  120.0
2026-01-03    NaN
2026-01-04  150.0
2026-01-05  130.0
2026-01-06    NaN
2026-01-07    NaN
2026-01-08  180.0
2026-01-09  200.0

In [ ]:
#5,6
print(df.rolling(window=3).mean())
#cannot conclude the highest average

            Sales
2026-01-01    NaN
2026-01-02    NaN
2026-01-03    NaN
2026-01-04    NaN
2026-01-05    NaN
2026-01-06    NaN
2026-01-07    NaN
2026-01-08    NaN
2026-01-09    NaN

Q6

In [ ]:
#1,2,3,4
P = np.array([ [1, 2], [4, 6], [7, 3], [2, 8], [9, 5] ])  
A=P[:,np.newaxis,:]
B=P[np.newaxis,:,:]
c=A-B
d=c**2
e=np.sum(d,axis=2)
f=np.sqrt(e)
f

array([[0.        , 5.        , 6.08276253, 6.08276253, 8.54400375],
       [5.        , 0.        , 4.24264069, 2.82842712, 5.09901951],
       [6.08276253, 4.24264069, 0.        , 7.07106781, 2.82842712],
       [6.08276253, 2.82842712, 7.07106781, 0.        , 7.61577311],
       [8.54400375, 5.09901951, 2.82842712, 7.61577311, 0.        ]])

In [72]:
#5
print(np.unravel_index(np.argmax(f),f.shape))

(np.int64(0), np.int64(4))